// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxAQ3pG4e6By1ySDllCJnuKHB-CNJOKo',
    appId: '1:405431864502:web:47daa78a0f30a6e4632a17',
    messagingSenderId: '405431864502',
    projectId: 'movieticketapp-7d5dc',
    authDomain: 'movieticketapp-7d5dc.firebaseapp.com',
    storageBucket: 'movieticketapp-7d5dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qIvLTQVitKcOdEkqfa9AkxEYOca0Aug',
    appId: '1:405431864502:android:76161bfcb5a0675d632a17',
    messagingSenderId: '405431864502',
    projectId: 'movieticketapp-7d5dc',
    storageBucket: 'movieticketapp-7d5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5P-_kfLbgfSOPbkm7Z5h88C2bfO9EmU',
    appId: '1:405431864502:ios:fcf8ceae0de0a5b6632a17',
    messagingSenderId: '405431864502',
    projectId: 'movieticketapp-7d5dc',
    storageBucket: 'movieticketapp-7d5dc.appspot.com',
    iosBundleId: 'com.example.movieBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf5P-_kfLbgfSOPbkm7Z5h88C2bfO9EmU',
    appId: '1:405431864502:ios:cff41f31edff8821632a17',
    messagingSenderId: '405431864502',
    projectId: 'movieticketapp-7d5dc',
    storageBucket: 'movieticketapp-7d5dc.appspot.com',
    iosBundleId: 'com.example.movieBooking.RunnerTests',
  );
}
